---
book_repo: pivotal-cf/docs-book-mysql
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-mysql
    ref: 1.9.0
  directory: p-mysql/1-9
  subnav_template: mysql_subnav_1_9.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    changelog_href: http://docs.pivotal.io/p-mysql/1-9/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: MySQL for PCF
    search_placeholder: Search MySQL for PCF 1.9
    url_prefix: p-mysql/1-9
    local_product_version: 1.9
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-mysql/1-8
        display_name: v1.8
      - url_prefix: http://docs.pivotal.io/p-mysql/1-7
        display_name: v1.7
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.6.pdf">v1.6</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.5.pdf">v1.5</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.4.pdf">v1.4</a>
- repository:
    name: pivotal-cf/docs-mysql
    ref: 1.8.0
  directory: p-mysql/1-8
  subnav_template: mysql_subnav_1_8.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    changelog_href: http://docs.pivotal.io/p-mysql/1-8/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: MySQL for PCF
    search_placeholder: Search MySQL for PCF 1.8
    url_prefix: p-mysql/1-8
    local_product_version: 1.8
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-mysql/1-9
        display_name: v1.9
      - url_prefix: http://docs.pivotal.io/p-mysql/1-7
        display_name: v1.7
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.6.pdf">v1.6</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.5.pdf">v1.5</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.4.pdf">v1.4</a>
- repository:
    name: pivotal-cf/docs-mysql
    ref: '1.7'
  directory: p-mysql/1-7
  subnav_template: mysql_subnav_1_7.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    changelog_href: http://docs.pivotal.io/p-mysql/1-7/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: MySQL for PCF
    search_placeholder: Search MySQL for PCF 1.7
    url_prefix: p-mysql/1-7
    local_product_version: 1.7
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-mysql/1-9
        display_name: v1.9
      - url_prefix: http://docs.pivotal.io/p-mysql/1-8
        display_name: v1.8
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.6.pdf">v1.6</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.5.pdf">v1.5</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.4.pdf">v1.4</a>
